import pdb

x = [1, 2, 3]
y = 8
z = 5

result1 = y + z

# Para colocar el debugger donde creo podr√≠a estar el error y estudiarlo sin un print

pdb.set_trace()
result2 = x + y

